-- MySQL Script generated by MySQL Workbench
-- Fri Jul 14 23:04:52 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ecommerceDB
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ecommerceDB` ;

-- -----------------------------------------------------
-- Schema ecommerceDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ecommerceDB` DEFAULT CHARACTER SET utf8 ;
USE `ecommerceDB` ;

-- -----------------------------------------------------
-- Table `General_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `General_user` ;

CREATE TABLE IF NOT EXISTS `General_user` (
  `trackingId` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`trackingId`),
  UNIQUE INDEX `trackingId_UNIQUE` (`trackingId` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Account` ;

CREATE TABLE IF NOT EXISTS `Account` (
  `accountId` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `creationTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `sessionData` VARCHAR(255) NOT NULL,
  `acc_trackingId` INT UNSIGNED NOT NULL,
  `lastlogin` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`accountId`),
  UNIQUE INDEX `accountId_UNIQUE` (`accountId` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  UNIQUE INDEX `trackingId_UNIQUE` (`acc_trackingId` ASC) VISIBLE,
  CONSTRAINT `acc_trackingId`
    FOREIGN KEY (`acc_trackingId`)
    REFERENCES `General_user` (`trackingId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Sessions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Sessions` ;

CREATE TABLE IF NOT EXISTS `Sessions` (
  `sessionId` VARCHAR(36) NOT NULL,
  `sessionStart` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `sessionStop` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `seesion_accountId` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`sessionId`),
  UNIQUE INDEX `sessionId_UNIQUE` (`sessionId` ASC) VISIBLE,
  INDEX `accountId_idx` (`seesion_accountId` ASC) VISIBLE,
  UNIQUE INDEX `accountId_UNIQUE` (`seesion_accountId` ASC) VISIBLE,
  CONSTRAINT `session_accountId`
    FOREIGN KEY (`seesion_accountId`)
    REFERENCES `Account` (`accountId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `newsletter`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `newsletter` ;

CREATE TABLE IF NOT EXISTS `newsletter` (
  `subscriptionId` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `status` VARCHAR(20) NOT NULL,
  `newsltr_trackingId` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`subscriptionId`),
  UNIQUE INDEX `subscriptionId_UNIQUE` (`subscriptionId` ASC) VISIBLE,
  UNIQUE INDEX `trackingId_UNIQUE` (`newsltr_trackingId` ASC) VISIBLE,
  CONSTRAINT `newsltr_trackingId`
    FOREIGN KEY (`newsltr_trackingId`)
    REFERENCES `General_user` (`trackingId`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `service_ticket`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `service_ticket` ;

CREATE TABLE IF NOT EXISTS `service_ticket` (
  `ticketId` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `issue` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `status` VARCHAR(20) NOT NULL,
  `ticket_trackingId` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`ticketId`),
  UNIQUE INDEX `ticketId_UNIQUE` (`ticketId` ASC) VISIBLE,
  UNIQUE INDEX `trackingId_UNIQUE` (`ticket_trackingId` ASC) VISIBLE,
  CONSTRAINT `ticket_trackingId`
    FOREIGN KEY (`ticket_trackingId`)
    REFERENCES `General_user` (`trackingId`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Category` ;

CREATE TABLE IF NOT EXISTS `Category` (
  `categoryId` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(80) NULL,
  `parentId` INT UNSIGNED NULL,
  PRIMARY KEY (`categoryId`),
  UNIQUE INDEX `categoryId_UNIQUE` (`categoryId` ASC) VISIBLE,
  INDEX `parentId_idx` (`parentId` ASC) VISIBLE,
  CONSTRAINT `parentId`
    FOREIGN KEY (`parentId`)
    REFERENCES `Category` (`categoryId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `merchant`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `merchant` ;

CREATE TABLE IF NOT EXISTS `merchant` (
  `merchantId` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `store_name` VARCHAR(45) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NULL,
  `contact_details` VARCHAR(90) NULL,
  `buisness_info` VARCHAR(255) NULL,
  `merchant_trackingId` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`merchantId`),
  UNIQUE INDEX `trackingId_UNIQUE` (`merchant_trackingId` ASC) VISIBLE,
  CONSTRAINT `merchant_trackingId`
    FOREIGN KEY (`merchant_trackingId`)
    REFERENCES `General_user` (`trackingId`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Product` ;

CREATE TABLE IF NOT EXISTS `Product` (
  `productId` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `quantity` INT UNSIGNED NULL,
  `price` DECIMAL(10,2) UNSIGNED NULL,
  `description` VARCHAR(255) NULL,
  `main_image_url` VARCHAR(255) NOT NULL,
  `keywords` VARCHAR(45) NULL,
  `tags` VARCHAR(45) NULL,
  `product_categoryId` INT UNSIGNED NOT NULL,
  `product_merchantId` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`productId`),
  UNIQUE INDEX `productId_UNIQUE` (`productId` ASC) VISIBLE,
  INDEX `product_categoryId_idx` (`product_categoryId` ASC) VISIBLE,
  INDEX `product_merchantId_idx` (`product_merchantId` ASC) VISIBLE,
  CONSTRAINT `product_categoryId`
    FOREIGN KEY (`product_categoryId`)
    REFERENCES `Category` (`categoryId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `product_merchantId`
    FOREIGN KEY (`product_merchantId`)
    REFERENCES `merchant` (`merchantId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Manufacturer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Manufacturer` ;

CREATE TABLE IF NOT EXISTS `Manufacturer` (
  `manufacturerId` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `contact_info` VARCHAR(45) NOT NULL,
  `manufact_productId` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`manufacturerId`),
  UNIQUE INDEX `manufacturerId_UNIQUE` (`manufacturerId` ASC) VISIBLE,
  UNIQUE INDEX `productId_UNIQUE` (`manufact_productId` ASC) VISIBLE,
  CONSTRAINT `manufact_productId`
    FOREIGN KEY (`manufact_productId`)
    REFERENCES `Product` (`productId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `address` ;

CREATE TABLE IF NOT EXISTS `address` (
  `addressId` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `street` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `county` VARCHAR(45) NOT NULL,
  `state` VARCHAR(45) NOT NULL,
  `postalcode` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`addressId`),
  UNIQUE INDEX `addressId_UNIQUE` (`addressId` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Approved_User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Approved_User` ;

CREATE TABLE IF NOT EXISTS `Approved_User` (
  `approvedUserId` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `password` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `approv_addressId` INT UNSIGNED NOT NULL,
  `approv_trackingId` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`approvedUserId`),
  UNIQUE INDEX `idApproved User_UNIQUE` (`approvedUserId` ASC) VISIBLE,
  UNIQUE INDEX `trackingId_UNIQUE` (`approv_trackingId` ASC) VISIBLE,
  INDEX `addressId_idx` (`approv_addressId` ASC) VISIBLE,
  CONSTRAINT `approv_trackingId`
    FOREIGN KEY (`approv_trackingId`)
    REFERENCES `General_user` (`trackingId`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `approv_addressId`
    FOREIGN KEY (`approv_addressId`)
    REFERENCES `address` (`addressId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Review`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Review` ;

CREATE TABLE IF NOT EXISTS `Review` (
  `reviewId` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `creationDate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `rating` INT UNSIGNED NOT NULL,
  `feedback` VARCHAR(255) NOT NULL,
  `rev_productId` INT UNSIGNED NOT NULL,
  `rev_approvedUserId` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`reviewId`),
  UNIQUE INDEX `reviewId_UNIQUE` (`reviewId` ASC) VISIBLE,
  CONSTRAINT `rev_productId`
    FOREIGN KEY (`rev_productId`)
    REFERENCES `Product` (`productId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `rev_approvedUserId`
    FOREIGN KEY (`rev_approvedUserId`)
    REFERENCES `Approved_User` (`approvedUserId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `product_image`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `product_image` ;

CREATE TABLE IF NOT EXISTS `product_image` (
  `imageId` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `image_Url` VARCHAR(255) NOT NULL,
  `productimage_productId` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`imageId`),
  UNIQUE INDEX `imageId_UNIQUE` (`imageId` ASC) VISIBLE,
  CONSTRAINT `productimage_productId`
    FOREIGN KEY (`productimage_productId`)
    REFERENCES `Product` (`productId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Inventory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Inventory` ;

CREATE TABLE IF NOT EXISTS `Inventory` (
  `inventoryId` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `stock` INT NULL,
  `inventory_productId` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`inventoryId`),
  UNIQUE INDEX `idInventory_UNIQUE` (`inventoryId` ASC) VISIBLE,
  UNIQUE INDEX `productId_UNIQUE` (`inventory_productId` ASC) VISIBLE,
  CONSTRAINT `inventory_productId`
    FOREIGN KEY (`inventory_productId`)
    REFERENCES `Product` (`productId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cart`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cart` ;

CREATE TABLE IF NOT EXISTS `Cart` (
  `cartId` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `totalwotax` DECIMAL(10,2) ZEROFILL UNSIGNED NULL,
  `cart_trackingId` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`cartId`),
  UNIQUE INDEX `cartId_UNIQUE` (`cartId` ASC) VISIBLE,
  UNIQUE INDEX `trackingId_UNIQUE` (`cart_trackingId` ASC) VISIBLE,
  CONSTRAINT `cart_trackingId`
    FOREIGN KEY (`cart_trackingId`)
    REFERENCES `General_user` (`trackingId`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cart_detail`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cart_detail` ;

CREATE TABLE IF NOT EXISTS `Cart_detail` (
  `cartdetId` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Quantity` INT UNSIGNED NULL,
  `cartdet_productId` INT UNSIGNED NOT NULL,
  `cartdet_cartId` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`cartdetId`),
  UNIQUE INDEX `cartdetId_UNIQUE` (`cartdetId` ASC) VISIBLE,
  CONSTRAINT `cartdet_productId`
    FOREIGN KEY (`cartdet_productId`)
    REFERENCES `Product` (`productId`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `cartdet_cartId`
    FOREIGN KEY (`cartdet_cartId`)
    REFERENCES `Cart` (`cartId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shipping_address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shipping_address` ;

CREATE TABLE IF NOT EXISTS `shipping_address` (
  `ship_addressId` INT UNSIGNED NOT NULL,
  `shippingId` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`shippingId`),
  UNIQUE INDEX `shippingId_UNIQUE` (`shippingId` ASC) VISIBLE,
  CONSTRAINT `ship_addressId`
    FOREIGN KEY (`ship_addressId`)
    REFERENCES `address` (`addressId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `billing_address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `billing_address` ;

CREATE TABLE IF NOT EXISTS `billing_address` (
  `bill_addressId` INT UNSIGNED NOT NULL,
  `billingId` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  INDEX `addressId_idx` (`bill_addressId` ASC) VISIBLE,
  PRIMARY KEY (`billingId`),
  UNIQUE INDEX `billingId_UNIQUE` (`billingId` ASC) VISIBLE,
  CONSTRAINT `bill_addressId`
    FOREIGN KEY (`bill_addressId`)
    REFERENCES `address` (`addressId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shippingMethod`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shippingMethod` ;

CREATE TABLE IF NOT EXISTS `shippingMethod` (
  `shippingmethodId` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `cost` DECIMAL(10,2) UNSIGNED NOT NULL,
  `estimateddeliverytime` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`shippingmethodId`),
  UNIQUE INDEX `shippingmethodId_UNIQUE` (`shippingmethodId` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `orderr`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `orderr` ;

CREATE TABLE IF NOT EXISTS `orderr` (
  `orderId` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `orderStatus` VARCHAR(20) NOT NULL,
  `total_amount` DECIMAL(10,2) NULL,
  `paymentStatus` VARCHAR(20) NULL,
  `shipping_tracking` VARCHAR(255) NOT NULL,
  `order_trackingId` INT UNSIGNED NOT NULL,
  `order_billingId` INT UNSIGNED NOT NULL,
  `order_shippingId` INT UNSIGNED NOT NULL,
  `order_shippingmethodId` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`orderId`),
  UNIQUE INDEX `orderId_UNIQUE` (`orderId` ASC) VISIBLE,
  CONSTRAINT `order_trackingId`
    FOREIGN KEY (`order_trackingId`)
    REFERENCES `General_user` (`trackingId`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `order_shippingId`
    FOREIGN KEY (`order_shippingId`)
    REFERENCES `shipping_address` (`ship_addressId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `order_billingId`
    FOREIGN KEY (`order_billingId`)
    REFERENCES `billing_address` (`billingId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `order_shippingmethodId`
    FOREIGN KEY (`order_shippingmethodId`)
    REFERENCES `shippingMethod` (`shippingmethodId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `order_details`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `order_details` ;

CREATE TABLE IF NOT EXISTS `order_details` (
  `quantity` INT UNSIGNED NOT NULL,
  `orderdet_cartdId` INT UNSIGNED NOT NULL,
  `orderdet_orderId` INT UNSIGNED NOT NULL,
  `orderdet_productId` INT UNSIGNED NOT NULL,
  UNIQUE INDEX `cartdetId_UNIQUE` (`orderdet_cartdId` ASC) VISIBLE,
  UNIQUE INDEX `productId_UNIQUE` (`orderdet_productId` ASC) VISIBLE,
  UNIQUE INDEX `orderId_UNIQUE` (`orderdet_orderId` ASC) VISIBLE,
  CONSTRAINT `orderdet_cartId`
    FOREIGN KEY (`orderdet_cartdId`)
    REFERENCES `Cart` (`cartId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `orderdet_orderId`
    FOREIGN KEY (`orderdet_orderId`)
    REFERENCES `orderr` (`orderId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `orderdet_productId`
    FOREIGN KEY (`orderdet_productId`)
    REFERENCES `Product` (`productId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wishlist`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wishlist` ;

CREATE TABLE IF NOT EXISTS `wishlist` (
  `wishlistId` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `size` INT UNSIGNED NULL,
  `wish_approvedUserId` INT UNSIGNED NOT NULL,
  `wish_productId` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`wishlistId`),
  UNIQUE INDEX `wishlistId_UNIQUE` (`wishlistId` ASC) VISIBLE,
  CONSTRAINT `wish_approvedUserId`
    FOREIGN KEY (`wish_approvedUserId`)
    REFERENCES `Approved_User` (`approvedUserId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `wish_productId`
    FOREIGN KEY (`wish_productId`)
    REFERENCES `Product` (`productId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Discount`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Discount` ;

CREATE TABLE IF NOT EXISTS `Discount` (
  `discountId` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(45) NOT NULL,
  `discount_amount` DECIMAL(10,2) UNSIGNED NOT NULL,
  `valid_till` DATE NOT NULL,
  `valid_from` DATE NOT NULL,
  PRIMARY KEY (`discountId`),
  UNIQUE INDEX `discountId_UNIQUE` (`discountId` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `revenue`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `revenue` ;

CREATE TABLE IF NOT EXISTS `revenue` (
  `sales` INT UNSIGNED NULL,
  `revenue` DECIMAL(10,2) NULL,
  `profit` DECIMAL(10,2) NULL,
  `revenue_productId` INT UNSIGNED NOT NULL,
  `revenueId` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  UNIQUE INDEX `productId_UNIQUE` (`revenue_productId` ASC) VISIBLE,
  PRIMARY KEY (`revenueId`),
  UNIQUE INDEX `revenueId_UNIQUE` (`revenueId` ASC) VISIBLE,
  CONSTRAINT `revenue_productId`
    FOREIGN KEY (`revenue_productId`)
    REFERENCES `Product` (`productId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `payment_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `payment_type` ;

CREATE TABLE IF NOT EXISTS `payment_type` (
  `paymenttypeId` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `debit_credit` ENUM('debit', 'credit', 'false') NULL,
  `paypal` ENUM('true', 'false') NULL,
  `crypto` ENUM('true', 'false') NULL,
  PRIMARY KEY (`paymenttypeId`),
  UNIQUE INDEX `paymenttypeId_UNIQUE` (`paymenttypeId` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `payment_method`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `payment_method` ;

CREATE TABLE IF NOT EXISTS `payment_method` (
  `paymentmethodId` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `payment_details` VARCHAR(60) NULL,
  `method_trackingId` INT UNSIGNED NOT NULL,
  `method_paymenttypeId` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`paymentmethodId`),
  UNIQUE INDEX `paymentmethodId_UNIQUE` (`paymentmethodId` ASC) VISIBLE,
  UNIQUE INDEX `trackingId_UNIQUE` (`method_trackingId` ASC) VISIBLE,
  UNIQUE INDEX `paymenttypeId_UNIQUE` (`method_paymenttypeId` ASC) VISIBLE,
  CONSTRAINT `method_trackingId`
    FOREIGN KEY (`method_trackingId`)
    REFERENCES `General_user` (`trackingId`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `method_paymenttypeId`
    FOREIGN KEY (`method_paymenttypeId`)
    REFERENCES `payment_type` (`paymenttypeId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `payment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `payment` ;

CREATE TABLE IF NOT EXISTS `payment` (
  `paymentId` INT UNSIGNED NOT NULL,
  `amount` DECIMAL(10,2) NULL,
  `status` VARCHAR(20) NOT NULL,
  `pay_paymentmethodId` INT UNSIGNED NOT NULL,
  `pay_orderId` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`paymentId`),
  UNIQUE INDEX `idtable1_UNIQUE` (`paymentId` ASC) VISIBLE,
  UNIQUE INDEX `paymentmethodId_UNIQUE` (`pay_paymentmethodId` ASC) VISIBLE,
  UNIQUE INDEX `orderId_UNIQUE` (`pay_orderId` ASC) VISIBLE,
  CONSTRAINT `pay_orderId`
    FOREIGN KEY (`pay_orderId`)
    REFERENCES `orderr` (`orderId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `pay_paymentmethodId`
    FOREIGN KEY (`pay_paymentmethodId`)
    REFERENCES `payment_method` (`method_trackingId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `products_added`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `products_added` ;

CREATE TABLE IF NOT EXISTS `products_added` (
  `productadded_trackingId` INT UNSIGNED NOT NULL,
  `productadded_productId` INT UNSIGNED NOT NULL,
  CONSTRAINT `productadded_trackingId`
    FOREIGN KEY (`productadded_trackingId`)
    REFERENCES `General_user` (`trackingId`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `productadded_productId`
    FOREIGN KEY (`productadded_productId`)
    REFERENCES `Product` (`productId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `promotional`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `promotional` ;

CREATE TABLE IF NOT EXISTS `promotional` (
  `promotionalId` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `promo_discountId` INT UNSIGNED NOT NULL,
  `promo_productId` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`promotionalId`),
  UNIQUE INDEX `promotionalId_UNIQUE` (`promotionalId` ASC) VISIBLE,
  CONSTRAINT `productId`
    FOREIGN KEY (`promo_productId`)
    REFERENCES `Product` (`productId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `discountId`
    FOREIGN KEY (`promo_discountId`)
    REFERENCES `Discount` (`discountId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
